package com.hamon.kmp_pocketbase.codegen.internal.generator

import com.hamon.kmp_pocketbase.codegen.internal.parser.schema.CollectionSchema
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

internal class CollectionNamesGenerator {
    fun generate(packageName: String, collections: List<CollectionSchema>): GeneratedFile {
        val objectSpec = TypeSpec.objectBuilder("PocketbaseCollection")
            .addProperties(
                collections.map { schema ->
                    PropertySpec.builder(schema.name, String::class, KModifier.CONST)
                        .initializer("%S", schema.name)
                        .build()
                },
            )
            .build()

        val fileSpec = FileSpec.builder(packageName, "PocketbaseCollection")
            .addFileComment("AUTO-GENERATED by kmp-pocketbase-codegen — do not edit manually")
            .addType(objectSpec)
            .build()

        return GeneratedFile("PocketbaseCollection", fileSpec.toString())
    }
}