package com.hamon.kmp_pocketbase.codegen.internal.generator

import com.hamon.kmp_pocketbase.codegen.internal.toCamelCase
import com.hamon.kmp_pocketbase.codegen.internal.toPascalCase
import com.hamon.kmp_pocketbase.codegen.internal.parser.schema.CollectionSchema
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asTypeName

internal class DataClassGenerator(
    private val typeMapper: TypeMapper,
    private val generateParcelize: Boolean,
) {
    fun generate(packageName: String, schema: CollectionSchema): GeneratedFile {
        val className = "${schema.name.toPascalCase()}Record"
        val visibleFields = schema.fields.filter { !it.hidden }

        val constructorBuilder = FunSpec.constructorBuilder()
        val properties = mutableListOf<PropertySpec>()
        val extraImports = mutableListOf<Pair<String, String>>()

        visibleFields.forEach { field ->
            val mapped = typeMapper.map(field, schema.name) ?: return@forEach
            val propName = field.name.toCamelCase()
            val typeName = mapped.resolveTypeName(packageName)

            constructorBuilder.addParameter(
                ParameterSpec.builder(propName, typeName).apply {
                    mapped.defaultValue?.let { defaultValue(it) }
                }.build(),
            )

            properties.add(
                PropertySpec.builder(propName, typeName)
                    .initializer(propName)
                    .apply {
                        if (propName != field.name) {
                            addAnnotation(
                                AnnotationSpec.builder(ClassName("kotlinx.serialization", "SerialName"))
                                    .addMember("%S", field.name)
                                    .build(),
                            )
                        }
                    }
                    .build(),
            )

            mapped.import?.let { fqn ->
                val dot = fqn.lastIndexOf('.')
                extraImports.add(fqn.substring(0, dot) to fqn.substring(dot + 1))
            }
        }

        val classBuilder = TypeSpec.classBuilder(className)
            .addModifiers(KModifier.DATA)
            .addAnnotation(AnnotationSpec.builder(ClassName("kotlinx.serialization", "Serializable")).build())
            .primaryConstructor(constructorBuilder.build())
            .addProperties(properties)

        if (generateParcelize) {
            classBuilder
                .addAnnotation(ClassName(packageName, "PbParcelize"))
                .addSuperinterface(ClassName(packageName, "PbParcelable"))
        }

        val fileSpec = FileSpec.builder(packageName, className)
            .addFileComment("AUTO-GENERATED by kmp-pocketbase-codegen — do not edit manually")
            .addType(classBuilder.build())
            .apply { extraImports.forEach { (pkg, name) -> addImport(pkg, name) } }
            .build()

        return GeneratedFile(className, fileSpec.toString())
    }

    private fun MappedType.resolveTypeName(packageName: String): TypeName {
        val base = kotlinType.toPoetTypeName(packageName)
        return if (isNullable) base.copy(nullable = true) else base
    }

    private fun String.toPoetTypeName(packageName: String): TypeName = when (this) {
        "String" -> String::class.asTypeName()
        "Double" -> Double::class.asTypeName()
        "Int" -> Int::class.asTypeName()
        "Boolean" -> Boolean::class.asTypeName()
        "JsonElement" -> ClassName("kotlinx.serialization.json", "JsonElement")
        else -> if (startsWith("List<")) {
            val inner = removePrefix("List<").removeSuffix(">")
            LIST.parameterizedBy(inner.toPoetTypeName(packageName))
        } else {
            ClassName(packageName, this)
        }
    }
}