package com.hamon.kmp_pocketbase.codegen.internal.generator

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec

internal class EnumGenerator {
    fun generate(packageName: String, enumName: String, values: List<String>): GeneratedFile {
        val typeSpec = TypeSpec.enumBuilder(enumName)
            .addAnnotation(AnnotationSpec.builder(ClassName("kotlinx.serialization", "Serializable")).build())
            .apply { values.forEach { addEnumConstant(it) } }
            .build()

        val fileSpec = FileSpec.builder(packageName, enumName)
            .addFileComment("AUTO-GENERATED by kmp-pocketbase-codegen — do not edit manually")
            .addType(typeSpec)
            .build()

        return GeneratedFile(enumName, fileSpec.toString())
    }
}