package com.hamon.kmp_pocketbase.codegen.internal.generator

internal object ParcelableShimGenerator {
    private const val FILE_NAME = "PocketbaseParcelable"

    fun generate(packageName: String): Map<ShimTarget, GeneratedFile> = mapOf(
        ShimTarget.COMMON to GeneratedFile(FILE_NAME, commonExpect(packageName)),
        ShimTarget.ANDROID to GeneratedFile(FILE_NAME, androidActual(packageName)),
        ShimTarget.JVM to GeneratedFile(FILE_NAME, noOpActual(packageName)),
        ShimTarget.JS to GeneratedFile(FILE_NAME, noOpActual(packageName)),
        ShimTarget.WASM_JS to GeneratedFile(FILE_NAME, noOpActual(packageName)),
        ShimTarget.NATIVE to GeneratedFile(FILE_NAME, noOpActual(packageName)),
    )

    private fun commonExpect(packageName: String) = """
        |// AUTO-GENERATED by kmp-pocketbase-codegen — do not edit manually
        |package $packageName
        |
        |@Target(AnnotationTarget.CLASS)
        |@Retention(AnnotationRetention.BINARY)
        |expect annotation class PbParcelize()
        |
        |expect interface PbParcelable
    """.trimMargin()

    private fun androidActual(packageName: String) = """
        |// AUTO-GENERATED by kmp-pocketbase-codegen — do not edit manually
        |package $packageName
        |
        |actual typealias PbParcelize = kotlinx.parcelize.Parcelize
        |actual typealias PbParcelable = android.os.Parcelable
    """.trimMargin()

    private fun noOpActual(packageName: String) = """
        |// AUTO-GENERATED by kmp-pocketbase-codegen — do not edit manually
        |package $packageName
        |
        |@Target(AnnotationTarget.CLASS)
        |@Retention(AnnotationRetention.BINARY)
        |actual annotation class PbParcelize actual constructor()
        |
        |actual interface PbParcelable
    """.trimMargin()
}

internal enum class ShimTarget {
    COMMON, ANDROID, JVM, JS, WASM_JS, NATIVE
}